before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then cp config/database.travis.mysql.yml config/database.yml; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then cp config/database.travis.pgsql.yml config/database.yml; fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then cp config/database.travis.sqlite.yml config/database.yml; fi"
  - sh -c "if [ '$DB' != 'sqlite' ]; then bundle exec rake db:create; fi"
  - npm install
env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite
  global:
    - SECRET_TOKEN=d6054cf90db212c8fbc070c896c30398e3275532c5602bdf00cb153b806c000e4e46fac2f3acc0783822b8f6d30b5913b6fbcfdd24914553e745b8aa8ddfa5a4
    - DEFAULT_URL=http://www.test-url.com
script:
  - npm test
  - bundle exec rake
language: ruby
cache:
  bundler: true
  directories:
    - node_modules
addons:
  postgresql: "9.3"
rvm:
  - ruby-2.1.1
